apiVersion: v1
kind: ConfigMap
metadata:
  name: "echo-rmq-cluster"
  namespace: echo-dev
  labels:
    app: "echo-rmq-cluster"
    enviroment: "dev"
    version: "1.0"
data:
  LOG_LEVEL: "DEBUG"
  RMQ_PORT:  "172.20.244.153:5672/"  #"rabbitmq-cluster.test-a.svc.cluster.local:5672/" # "10.102.42.237:5672/" # rabbitmq-cluster.msg.svc.cluster.local
  RMQ_QUEUE: "task_queue"
  DURATION: "2000"
