apiVersion: v1
kind: ConfigMap
metadata:
  name: &component-name echo-rmq-cluster
  namespace: echo-dev
  labels:
    app: *component-name
    enviroment: "dev"
    version: "1.0"
data:
  LOG_LEVEL: "DEBUG"
  RMQ_PORT:  "172.20.237.165:5672/"  #"rabbitmq-cluster.test-a.svc.cluster.local:5672/" # "10.102.42.237:5672/" # rabbitmq-cluster.msg.svc.cluster.local
  RMQ_QUEUE: "queue_person_quorum"
  DURATION: "1000"                  # time to producer msg
  TIME_DELAY_QUEUE: "2000"          # time to consume msg
