apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &component-name rmq-external-secret
  namespace: echo-dev
  labels:
    app: *component-name
    enviroment: "dev"
    version: "1.0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: echo-rmq-cluster-secretstore
    kind: SecretStore
  target:
    name: echo-rmq-external-secret # Name of External Secret created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: EchoRMQClusterAccess # AWS Secret Manager (secret-name)