apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-rmq-cluster-sa
  namespace: echo-dev
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::184397147467:role/EchoRMQClusterRole"