apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app-name go-rmq-consumer
  namespace: test-a
  labels:
    app: *app-name
    enviroment: dev
    version: "1.0"
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: *app-name
  template:
    metadata:
      labels:
        app: *app-name
        enviroment: dev
        version: "1.0"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
      - name: *app-name
        image: 908671954593.dkr.ecr.us-east-2.amazonaws.com/go-rmq-consumer:latest
        resources:
           requests:
             cpu: 100m
             memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps"
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps"
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        env:
          - name: RMQ_USER
            valueFrom:
              secretKeyRef:
                name: go-rmq-consumer-external-secret
                key: RMQ_USER
          - name: RMQ_PASS
            valueFrom:
              secretKeyRef:
                name: go-rmq-consumer-external-secret
                key: RMQ_PASS
        envFrom:
          - configMapRef:
              name: go-rmq-consumer-cm
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                  matchLabels:
                    app: *app-name
                    environment: dev
              topologyKey: topology.kubernetes.io/zone
            weight: 100