apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &component-name go-rmq-producer-st
  namespace: test-a
  labels:
    app: *component-name
    enviroment: dev
    version: "1.0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awsssm-rmq-secretstore
    kind: SecretStore
  target:
    name: go-rmq-producer-external-secret # Name Secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rmq-secret # AWS Secret Manager (secret-name)