apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: &component-name keda-trigger-go-rmq-consumer-auth
  namespace: test-a
  labels:
    app: *component-name
    enviroment: dev
    version: "1.0"
spec:
  secretTargetRef:
    - parameter: host
      name: go-rmq-consumer-external-secret
      key: RMQ_URL
