apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: &component-name keda-go-rmq-consumer-scale
  namespace: test-a
  labels:
    app: *component-name
    enviroment: dev
    version: "1.0"
spec:
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true              # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  scaleTargetRef:
    name: go-rmq-consumer
  triggers:
  - type: rabbitmq
    metadata:
      #host: amqp://guest:guest@rabbitmq-cluster.test-a:5672/ # local-test
      protocol: amqp
      queueName: queue_person_quorum
      mode: QueueLength
      value: "10"
      metricName: custom-testqueue # DEPRECATED: This parameter is deprecated as of KEDA v2.10 and will be removed in version `2.12`. optional. Generated value would be `rabbitmq-custom-testqueue`
    authenticationRef:
      name: keda-trigger-go-rmq-consumer-auth
  minReplicaCount: 0
  maxReplicaCount: 3
  pollingInterval: 5
  cooldownPeriod: 30