apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: &component-name keda-rabbitmq-scale
  namespace: test-a
  labels:
    app: *component-name
    enviroment: dev
    version: "1.0"
spec:
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true              # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  scaleTargetRef:
    name: go-rmq-consumer
  triggers:
  - type: rabbitmq
    metadata:
      #host: amqp://guest:guest@172.20.244.153:5672/ # local-test
      protocol: amqp
      queueName: queue_person_quorum
      mode: QueueLength
      value: "20"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 10
  cooldownPeriod: 60