apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: awsssm-rmq-secretstore
  namespace: test-a
  labels:
    app: awsssm-rmq-secretstore
    enviroment: dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: rmq-sa