# docker build -t dock-rabbitmq . -f dockerfile-rabbitmq

FROM rabbitmq:3.11.1-management

RUN apt update -y && apt install wget -y
RUN cd /opt/rabbitmq/plugins \
     && wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez  \
     && rabbitmq-plugins enable rabbitmq_delayed_message_exchange

EXPOSE 15671 15672