# docker network create --driver bridge go_net
# docker build -t go-rmq-consumer . -f dockerfile-consumer

FROM golang:1.18 As builder

WORKDIR /app
COPY . .

WORKDIR /app/cmd/consumer

RUN go build -o go-rmq-consumer -ldflags '-linkmode external -w -extldflags "-static"'
#RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w' -o go_kafka_consumer # alpine

FROM alpine
WORKDIR /app
COPY --from=builder /app/cmd/consumer/go-rmq-consumer .
CMD ["/app/go-rmq-consumer"]