apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rmq-producer
  namespace: test-a
  labels:
    app: "go-rmq-producer"
    version: "1.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-rmq-producer
  template:
    metadata:
      labels:
        app: go-rmq-producer
        version: "1.0"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
      - name: go-rmq-producer
        imagePullPolicy: Never
        image: go-rmq-producer:latest
        resources:
           requests:
             cpu: 100m
             memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps"
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps"
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        env:
          - name: RMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster
                key: RMQ_USER
          - name: RMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster
                key: RMQ_PASS
        envFrom:
          - configMapRef:
              name: go-rmq-cm
      terminationGracePeriodSeconds: 60
