apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-external-rabbimq
  name: svc-external-rabbimq
  namespace: msg
spec:
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 0
  selector: {}
