apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim
  namespace: echo-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rmq-efs
  resources:
    requests:
      storage: 10Mi